name: GitHub Pipeline for HW22

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
         java-version: '17'
         distribution: 'temurin'
      - name: Compile project
        run: mvn --batch-mode compile
  test:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test project
        run: mvn --batch-mode test
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Package project
        run: mvn --batch-mode package
